### ISSUE TITLE
Bug: Titles disappear when zooming (or changing dpi)

### ISSUE THREAD

**Issue by nytamin** [christianeide/github-sidebar#13]
How to reproduce:

- Using Chrome
- Open github page, the sidebar looks good
- Zoom the web page (ctrl+scroll or ctrl+plus)

The titles disappear, like so:
![image](https://user-images.githubusercontent.com/15196563/58863756-b7a7b480-86b3-11e9-8ce2-860c9d9aa932.png)

When restoring zoom level, the titles are still gone.

Possible fix; for me locally, this resolves the issue:
Change
```
#github-sidebar .sidebar main .repositories .repository .repoHeading .icon {
    min-width: min-content;
}
```
to
```
#github-sidebar .sidebar main .repositories .repository .repoHeading .icon {
    min-width: auto;
}
```

**Comment by christianeide** [comment]
Yeah, nice feature :) Thank you for your bugreport, I have been able to reproduce, will take a look at it as soon as I can.

**Comment by christianeide** [comment]
Fixed in v.1.1.4

Released to chrome store, should be autoupdated soon
